<?php

/**
 * @file
 * Panelizer Variant Module File.
 */

require_once 'includes/panelizer_variant.custom.inc';

/**
 * Implements hook_menu().
 */
function panelizer_variant_menu() {
  $items = array();

  $items['admin/config/content/panelizer_variant'] = array(
    'title' => 'Panelizer Variant',
    'description' => 'Configuration for Panelizer Variant',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('panelizer_variant_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'panelizer_variant.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_entity_info_alter().
 */
function panelizer_variant_entity_info_alter(&$entity_info) {
  $view_modes = _panelizer_variant_view_modes_select();

  foreach ($view_modes as $view_mode => $value) {
    $entity_info['node']['view modes'][$view_mode] = array(
      'label' => $value,
      'custom settings' => TRUE,
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function panelizer_variant_form_panelizer_default_context_form_alter(&$form, &$form_state, $form_id) {
  $view_modes = _panelizer_variant_view_modes_select();

  foreach (array_keys($view_modes) as $key) {
    if ($key == $form_state['panelizer']->view_mode) {
      $form['right']['variant'] = array(
        '#weight' => -1,
      );

      $form['right']['variant']['use_variant'] = array(
        '#markup' => t('<p><strong>NOTE: YOU MUST SELECT A CONTEXT</strong></p>
           <p>If you have not set up view modes, you can do it on the
           <a href="/admin/config/content/panelizer_variant">Panelizer Variant
           Setting Page</a></p><p> Then go to your <a href="/admin/structure/types">
           Content Types</a> and add the view modes to the content type.</p>'),
        '#prefix' => '<div id="ctools-variant-table"><table id="variant-table"><thead><tr><th class="title">Variant Info</th></tr></thead><tbody><tr><td>',
        '#suffix' => '</td></tr></tbody></table></div>',
      );

      $form['#validate'][] = '_panelizer_variant_custom_validate';
      $form['#submit'][] = '_panelizer_variant_custom_submit';
    }
  }
}

/**
 * Custom Validator for form.
 */
function _panelizer_variant_custom_validate($form, &$form_state) {
  if (!isset($form_state['panelizer']->contexts[0])) {
    form_set_error('right][variant',
      t('You must select a context when using a Variant View Mode'));
  }
}

/**
 * Custom SUBMIT for form.
 */
function _panelizer_variant_custom_submit($form, &$form_state) {
  $values = array();
  foreach ($form_state['panelizer']->contexts as $key) {
    $values[] = array(
      'name' => $key['keyword'],
      'entity_id' => $key['entity_id'],
    );
  }
  $name = $form_state['panelizer']->name;
  $data = array(
    'name' => $name,
    'variant' => $values,
  );
  $exist = db_query('SELECT name FROM {panelizer_variant} WHERE name = :name', array(':name' => $name))->rowCount();
  if ($exist > 0) {
    drupal_write_record('panelizer_variant', $data, 'name');
  }
  else {
    drupal_write_record('panelizer_variant', $data);
  }
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function panelizer_variant_entity_view_mode_alter(&$view_mode, $context) {
  $entity = _panelizer_variant_entity_render($context);
  if ($entity['panelized']) {
    $view_mode = $entity['view_mode'];
  }
}
